USE bakery_db;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone   VARCHAR(30)   DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dob     DATE          DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS country VARCHAR(100)  DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS city    VARCHAR(100)  DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS postal  VARCHAR(20)   DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS photo   MEDIUMTEXT    DEFAULT NULL;
